supervises.ExitError: remove duplicate argv string
The Argv was set on command lookup/shellparse errors to the passed in
command, otherwise to the exec.Cmd string for returning the failing
command to the user. Remove and always use the exec.Cmd.String().